name: xcube
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.6
  # Required
  - affine >=2.2
  - click >=7.0
  - cmocean >=2.0
  - dask >=1.2
  - fiona >=1.8
  - gdal >=3.0,<3.1
  - geopandas >=0.8
  - jdcal >=1.4.1
  - jsonschema >=3.2.0
  - matplotlib-base >=3.0
  - netcdf4 >=1.5.0
  - numba >=0.43
  - numpy >=1.16
  - pandas >=1.1
  - pillow >=6.0
  - pyjwt >=1.7
  - pyyaml >=5.1
  - rasterio >=1.0
  - s3fs >=0.5.1
  - scipy >=1.2
  - setuptools >=41.0
  - shapely >=1.6
  - sphinx >=2.0.1
  - strict-rfc3339 >=0.7 # for python-jsonschema date-time format validation
  - tornado >=6.0
  - xarray >=0.16.1
  - zarr >=2.6.1
  # Testing
  - flake8 >=3.7
  - moto >=1.3
  - pytest >=4.4
  - pytest-cov >=2.6
  - requests-mock >=1.8.0
